# Generated by Django 5.2.4 on 2026-08-10 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_accesscontrol_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_emails', models.BooleanField(default=True)),
                ('activity_reports', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('show_help_tooltips', models.BooleanField(default=True)),
                ('compact_tables', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
